export const types = {
    SEARCH_USERS_REQUEST: 'SEARCH_USERS_REQUEST',
    SEARCH_USERS_SUCCESS: 'SEARCH_USERS_SUCCESS',
    SEARCH_USERS_FAILURE:'SEARCH_USERS_FAILURE',
    SEARCH_POKEMON_REQUEST: 'SEARCH_POKEMON_REQUEST',
    SEARCH_POKEMON_SUCCESS: 'SEARCH_POKEMON_SUCCESS',
    SEARCH_POKEMON_FAILURE:'SEARCH_POKEMON_FAILURE',

}